# Generated by Django 4.2.2 on 2023-07-09 11:39

from django.db import migrations

from gisapp.utils import load_data

class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
